version: "1"
services:
  kobe:
    build:
      context: .
      dockerfile: kobe.Dockerfile
    ports:
      - 3001:3000
  nginx-app:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - 4000:80
  jordan:
    image: jordan
    ports:
      - 3004:3000
